version: "1"
projects:
- name: East Coast E-Bike Warranty Claims Repair Center LLC
  environments:
  - name: Production
    services:
    - type: web
      name: warranty-hub
      runtime: python
      repo: https://github.com/mikey83mikey83-42/main.py
      plan: free
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
      autoDeployTrigger: commit
